# Generated by Django 4.2.5 on 2023-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('boarduser', 'Boarduser'), ('taker', 'Taker'), ('admin', 'Admin')], default='boarduser', max_length=20),
        ),
    ]
