# Generated by Django 4.2.5 on 2023-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardingform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pettype', models.CharField(max_length=12)),
                ('nuberofpetboarded', models.IntegerField()),
                ('petbreed', models.CharField(max_length=200)),
                ('petsize', models.CharField(max_length=200)),
                ('additionalinfo', models.CharField(max_length=240)),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
