# Generated by Django 4.2.5 on 2023-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0006_alter_boardingform_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingform',
            name='startdate',
            field=models.DateField(),
        ),
    ]
