# Generated by Django 4.2.7 on 2023-11-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0009_alter_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
