# Generated by Django 4.2.7 on 2023-11-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0012_user_roles_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('boarduser', 'Boarduser'), ('taker', 'Taker'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
