# Generated by Django 4.2.7 on 2023-12-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0014_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='userprofileimage/'),
        ),
    ]
