# Generated by Django 4.2.7 on 2023-12-14 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0015_user_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingform',
            name='boardinguser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
