# Generated by Django 4.2.7 on 2023-12-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0016_boardingform_boardinguser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardingform',
            old_name='boardinguser',
            new_name='user',
        ),
    ]
