# Generated by Django 4.2.7 on 2023-12-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0017_rename_boardinguser_boardingform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_and_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
