# Generated by Django 4.2.7 on 2023-12-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0018_user_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepttaker',
            field=models.BooleanField(default=False),
        ),
    ]
