# Generated by Django 4.2.7 on 2024-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0020_remove_user_accepttaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingform',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
