# Generated by Django 4.2.5 on 2023-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TakerAbotpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indroduction', models.CharField(max_length=255)),
                ('petexperience', models.CharField(max_length=255)),
                ('enjoyment_or', models.CharField(max_length=255)),
                ('skillandqualification', models.CharField(max_length=255)),
            ],
        ),
    ]
