# Generated by Django 4.2.7 on 2023-11-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeridproof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proofimage', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Takerwithpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakerwithIdform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adharimg', models.ImageField(upload_to='adharimg/')),
                ('otheridimg', models.ImageField(null=True, upload_to='otheridimg/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DescribeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=255)),
                ('petcount', models.CharField(max_length=20)),
                ('acceptingpet', models.CharField(max_length=12)),
                ('acceptingpetsize', models.CharField(max_length=20)),
                ('howmanywalk', models.CharField(max_length=8)),
                ('apartmentorhome', models.CharField(max_length=20)),
                ('transportemergencies', models.CharField(max_length=10)),
                ('sleepinglocation', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
