# Generated by Django 4.2.5 on 2023-10-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0002_takerabotpage_otherpetqualifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takerabotpage',
            old_name='enjoyment_or',
            new_name='skillandqualifications',
        ),
        migrations.RenameField(
            model_name='takerabotpage',
            old_name='skillandqualification',
            new_name='workstatus',
        ),
    ]
