# Generated by Django 4.2.5 on 2023-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0004_rename_indroduction_takerabotpage_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescribeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=255)),
                ('petcount', models.CharField(max_length=20)),
                ('acceptingpet', models.CharField(max_length=12)),
                ('acceptingpetsize', models.CharField(max_length=20)),
                ('howmanywalk', models.CharField(max_length=8)),
                ('apartmentorhome', models.CharField(max_length=20)),
                ('transportemergencies', models.CharField(max_length=10)),
                ('sleepinglocation', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
