# Generated by Django 4.2.7 on 2023-11-07 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petcare', '0004_alter_takerabotpag_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Takerwithpet',
            new_name='Takerwithpets',
        ),
    ]
