# Generated by Django 4.2.5 on 2023-10-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0006_takerproofimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TakerProofimages',
            new_name='Takerwithpet',
        ),
    ]
