# Generated by Django 4.2.7 on 2023-11-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0006_alter_takerabotpag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takerabotpag',
            options={'verbose_name': 'Taker Abotpag', 'verbose_name_plural': 'Taker Abotpag'},
        ),
    ]
