# Generated by Django 4.2.7 on 2023-11-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0007_alter_takerabotpag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='describeservice',
            options={'verbose_name': 'Describe service', 'verbose_name_plural': 'Describe service'},
        ),
    ]
