# Generated by Django 4.2.7 on 2023-11-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0008_alter_describeservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='describeservice',
            options={'verbose_name': 'DescribeService', 'verbose_name_plural': 'DescribeService'},
        ),
    ]
