# Generated by Django 4.2.5 on 2023-10-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0008_describeservice_user_takerabotpage_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeridproof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proofimage', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
