# Generated by Django 4.2.7 on 2023-11-07 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petcare', '0009_alter_describeservice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescribeServicetwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=255)),
                ('petcount', models.CharField(max_length=20)),
                ('acceptingpet', models.CharField(max_length=12)),
                ('acceptingpetsize', models.CharField(max_length=20)),
                ('howmanywalk', models.CharField(max_length=8)),
                ('apartmentorhome', models.CharField(max_length=20)),
                ('transportemergencies', models.CharField(max_length=10)),
                ('sleepinglocation', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
