# Generated by Django 4.2.5 on 2023-10-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0010_alter_takeridproof_proofimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeridproof',
            name='proofimage',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
