# Generated by Django 4.2.7 on 2023-11-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0010_describeservicetwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describeservicetwo',
            name='pincode',
            field=models.CharField(max_length=255),
        ),
    ]
