# Generated by Django 4.2.7 on 2024-01-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0021_boardingform_pincode'),
        ('petcare', '0012_takerwithidform_takeraccept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bothusersrequestfeild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petboarding.boardingform')),
                ('tkerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petcare.takerwithidform')),
                ('tkrdescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petcare.describeservicetwo')),
            ],
        ),
    ]
