# Generated by Django 4.2.7 on 2024-01-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0014_invitation_delete_bothusersrequestfeild'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
