# Generated by Django 4.2.7 on 2024-01-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petboarding', '0021_boardingform_pincode'),
        ('petcare', '0018_remove_invitation_user_alter_invitation_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='boardingform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petboarding.boardingform'),
        ),
    ]
